modLoader = "javafml"
loaderVersion = "[42,)"
issueTrackerURL="https://github.com/Sunekaer/Simple-Discord-Rich-Presence/issues"
license="All Rights Reserved"

[[mods]]
modId="sdrp"
displayTest="IGNORE_ALL_VERSION"
version="${version}"
displayName="Simple Discord Rich Presence"
displayURL="https://www.curseforge.com/minecraft/mc-mods/simple-discord-rich-presence"
logoFile="logo.png"
authors="Sunekaer"
description='''
Simple Discord Rich Presence
'''

[[dependencies.sdrp]]
modId = "forge"
mandatory = true
versionRange = "[42,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sdrp]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sdrp]]
modId = "architectury"
mandatory = true
versionRange = "[6.0.34,)"
ordering = "AFTER"
side = "BOTH"
