modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL="https://github.com/Sunekaer/Simple-Discord-Rich-Presence/issues"
license="All Rights Reserved"

[[mods]]
modId="sdrp"
displayTest="IGNORE_ALL_VERSION"
version="${version}"
displayName="Simple Discord Rich Presence"
displayURL="https://www.curseforge.com/minecraft/mc-mods/simple-discord-rich-presence"
logoFile="logo.png"
authors="Sunekaer"
description='''
Simple Discord Rich Presence
'''

[[dependencies.sdrp]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sdrp]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sdrp]]
modId = "architectury"
mandatory = true
versionRange = "[7.0.65,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sdrp]]
modId = "cloth_config"
mandatory = true
versionRange = "[9.0.94,)"
ordering = "NONE"
side = "BOTH"
