modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL="https://github.com/nanite/Simple-Discord-Rich-Presence"
license="All Rights Reserved"

[[mods]]
modId="sdrp"
displayTest="IGNORE_ALL_VERSION"
version="${version}"
displayName="Simple Discord Rich Presence"
displayURL="https://www.curseforge.com/minecraft/mc-mods/simple-discord-rich-presence"
logoFile="logo.png"
authors="Sunekaer"
description='''
Simple Discord Rich Presence
'''

[[dependencies.sdrp]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sdrp]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sdrp]]
modId = "architectury"
mandatory = true
versionRange = "[4.6.77,)"
ordering = "AFTER"
side = "BOTH"
