modLoader="javafml" 
loaderVersion="[28,)" 
issueTrackerURL="http://my.issue.tracker/"
[[mods]] 
modId="sdrp" 
version="${file.jarVersion}" 
displayName="Simple Discord Rich Presence" 
displayURL="http://example.com/" 
logoFile="logo.png" #optional
authors="Sunekaer" #optional
description='''
Simple Discord Rich Presence
'''
[[dependencies.sdrp]] #optional
    modId="forge" 
    mandatory=true 
    versionRange="[28.0.45,)" 
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.sdrp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
