modLoader="javafml" 
loaderVersion="[32,)"
issueTrackerURL="https://github.com/Sunekaer/Simple-Discord-Rich-Presence/issues"
[[mods]] 
modId="sdrp" 
version="${file.jarVersion}" 
displayName="Simple Discord Rich Presence" 
displayURL="https://www.curseforge.com/minecraft/mc-mods/simple-discord-rich-presence"
logoFile="logo.png"
authors="Sunekaer"
description='''
Simple Discord Rich Presence
'''
[[dependencies.sdrp]] #optional
    modId="forge"
    mandatory=true
    versionRange="[32.0.0,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.sdrp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
